kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: frontend
  namespace: default
  labels:
    run: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      run: frontend
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/colibriapp/front-image
          ports:
            - containerPort: 80
              protocol: TCP

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: backend-user
  namespace: default
  labels:
    run: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      run: backend-user
  template:
    metadata:
      labels:
        run: backend-user
    spec:
      containers:
        - name: backend-user
          image: gcr.io/colibriapp/api-users-image
          ports:
            - containerPort: 8000
              protocol: TCP

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: backend-posts
  namespace: default
  labels:
    run: backend-posts
spec:
  replicas: 2
  selector:
    matchLabels:
      run: backend-posts
  template:
    metadata:
      labels:
        run: backend-posts
    spec:
      containers:
        - name: backend-posts
          image: gcr.io/colibriapp/api-posts-image
          ports:
            - containerPort: 8001
              protocol: TCP